version: '3.8'

services:
  # Backend API
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - PINATA_API_KEY=${PINATA_API_KEY}
      - PINATA_SECRET_KEY=${PINATA_SECRET_KEY}
      - BLOCKCHAIN_RPC_URL=${BLOCKCHAIN_RPC_URL}
      - CONTRACT_ADDRESS=${CONTRACT_ADDRESS}
      - MARKETPLACE_ADDRESS=${MARKETPLACE_ADDRESS}
    networks:
      - app-network
    restart: unless-stopped

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://backend:5000
      - VITE_PINATA_API_KEY=${PINATA_API_KEY}
      - VITE_PINATA_SECRET_KEY=${PINATA_SECRET_KEY}
      - VITE_WEB3_RPC_URL=${BLOCKCHAIN_RPC_URL}
      - VITE_CONTRACT_ADDRESS=${CONTRACT_ADDRESS}
      - VITE_MARKETPLACE_ADDRESS=${MARKETPLACE_ADDRESS}
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

  # Hardhat Node (for development)
  hardhat:
    build:
      context: ./smart-contracts
      dockerfile: Dockerfile
    ports:
      - "8545:8545"
    command: npx hardhat node --hostname 0.0.0.0
    networks:
      - app-network
    profiles:
      - dev

networks:
  app-network:
    driver: bridge